"""index audit_logs tenant

Revision ID: 0005_audit_tenant_index
Revises: 0004_app_role
Create Date: 2026-09-01 09:26:48.906735+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0005_audit_tenant_index"
down_revision: str | None = "0004_app_role"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    # ### end Alembic commands ###
