"""order counters

Revision ID: 0006_order_counters
Revises: 0005_audit_tenant_index
Create Date: 2026-09-01 10:10:33.037965+00:00
"""

from __future__ import annotations

import os
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_rls_sql, enable_rls_sql

revision: str = "0006_order_counters"
down_revision: str | None = "0005_audit_tenant_index"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_counters",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(length=8), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "branch_id", "period"),
    )
    # ### end Alembic commands ###

    # A new TenantMixin table must not ship without its policy.
    for statement in enable_rls_sql("order_counters"):
        op.execute(statement)
    op.execute(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON order_counters TO "'
        + os.getenv("POSTGRES_USER", "pos_app")
        + '"'
    )


def downgrade() -> None:
    for statement in disable_rls_sql("order_counters"):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_counters")
    # ### end Alembic commands ###
