"""password reset tokens

Revision ID: 0007_password_reset
Revises: 0006_order_counters
Create Date: 2026-09-05 17:38:09.745490+00:00
"""

from __future__ import annotations

import os
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_rls_sql, enable_rls_sql

revision: str = "0007_password_reset"
down_revision: str | None = "0006_order_counters"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_password_reset_expires", "password_reset_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_tokens_tenant_id"),
        "password_reset_tokens",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # A new tenant-scoped table must not ship without its policy. This one
    # takes the auth-lookup escape: a reset is consumed by someone who is, by
    # definition, not signed in yet.
    for statement in enable_rls_sql("password_reset_tokens", allow_auth_lookup=True):
        op.execute(statement)
    op.execute(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON password_reset_tokens TO "'
        + os.getenv("POSTGRES_USER", "pos_app")
        + '"'
    )


def downgrade() -> None:
    for statement in disable_rls_sql("password_reset_tokens"):
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_tenant_id"), table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_expires", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
