"""payment transactions

Revision ID: 0008_payment_transactions
Revises: 0007_password_reset
Create Date: 2026-09-05 18:02:38.806822+00:00
"""

from __future__ import annotations

import os
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0008_payment_transactions"
down_revision: str | None = "0007_password_reset"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_transactions",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider", sa.Enum("PAYME", "CLICK", "MANUAL", name="payment_provider"), nullable=False
        ),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column(
            "state",
            sa.Enum("CREATED", "PERFORMED", "CANCELLED", "REFUNDED", name="transaction_state"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_time", sa.BigInteger(), nullable=True),
        sa.Column("performed_time", sa.BigInteger(), nullable=True),
        sa.Column("cancelled_time", sa.BigInteger(), nullable=True),
        sa.Column("cancel_reason", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invoice_id"], ["subscription_invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_payment_tx_provider_external"),
    )
    op.create_index(
        op.f("ix_payment_transactions_external_id"),
        "payment_transactions",
        ["external_id"],
        unique=False,
    )
    op.create_index("ix_payment_tx_invoice", "payment_transactions", ["invoice_id"], unique=False)
    op.create_index("ix_payment_tx_state", "payment_transactions", ["state"], unique=False)
    # ### end Alembic commands ###

    # Deliberately NOT under row-level security.
    #
    # A gateway calls in with no session and identifies the transaction by its
    # own id, before any tenant context exists. An RLS policy here would make
    # the row invisible to the only caller that needs it. Isolation instead
    # comes from the fact that a provider can only reference a transaction it
    # created, and every handler re-derives the tenant from the invoice.
    op.execute(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON payment_transactions TO "'
        + os.getenv("POSTGRES_USER", "pos_app")
        + '"'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payment_tx_state", table_name="payment_transactions")
    op.drop_index("ix_payment_tx_invoice", table_name="payment_transactions")
    op.drop_index(op.f("ix_payment_transactions_external_id"), table_name="payment_transactions")
    op.drop_table("payment_transactions")
    # ### end Alembic commands ###
